name: Deploy Phoenix

on:
  push:
    branches:
      - main

jobs:
  backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies & Build
        run: |
          cd Backend
          npm ci
          npm run build

      # dist 파일 및 package.json만 서버로 복사
      - name: Copy dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.BACK_HOST }}
          username: ${{ secrets.BACK_USER }}
          key: ${{ secrets.BACK_SSH_KEY }}
          source: "Backend/dist/*,Backend/package*.json"
          target: "/home/ubuntu/apps/Phoenix/Backend/"

      # 서버에서 pm2 restart
      - name: Restart backend with pm2
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.BACK_HOST }}
          username: ${{ secrets.BACK_USER }}
          key: ${{ secrets.BACK_SSH_KEY }}
          envs: APP_NAME,APP_VERSION,NODE_ENV,PORT,CORS_ORIGIN,API_URL,FRONTEND_URL,DB_HOST,DB_PORT,DB_USERNAME,DB_PASSWORD,DB_DATABASE,JWT_SECRET,JWT_EXPIRES_IN,OAUTH_REDIRECT_BASE,OAUTH_SUCCESS_REDIRECT,OAUTH_FAILURE_REDIRECT,GOOGLE_CLIENT_ID,GOOGLE_CLIENT_SECRET,GOOGLE_CALLBACK_URL,GOOGLE_CALLBACK_PATH,NAVER_CLIENT_ID,NAVER_CLIENT_SECRET,NAVER_CALLBACK_URL,NAVER_CALLBACK_PATH,NAVER_SERVICE_URL,KAKAO_CLIENT_ID,KAKAO_CLIENT_SECRET,KAKAO_CALLBACK_URL,KAKAO_CALLBACK_PATH,INITIAL_ADMIN_LOGIN_ID,INITIAL_ADMIN_PASSWORD,INITIAL_ADMIN_NAME,INITIAL_ADMIN_EMAIL,INITIAL_ADMIN_PHONE,AWS_ACCESS_KEY_ID,AWS_SECRET_ACCESS_KEY,AWS_REGION,AWS_SES_FROM_EMAIL,AWS_SES_TO_EMAIL,LOG_LEVEL
          script: |
            cd /home/ubuntu/apps/Phoenix/Backend

            # .env 파일 재작성
            cat > .env <<EOL
            APP_NAME=${APP_NAME}
            APP_VERSION=${APP_VERSION}
            NODE_ENV=${NODE_ENV}
            PORT=${PORT}
            CORS_ORIGIN=${CORS_ORIGIN}
            API_URL=${API_URL}
            FRONTEND_URL=${FRONTEND_URL}
            DB_HOST=${DB_HOST}
            DB_PORT=${DB_PORT}
            DB_USERNAME=${DB_USERNAME}
            DB_PASSWORD=${DB_PASSWORD}
            DB_DATABASE=${DB_DATABASE}
            JWT_SECRET=${JWT_SECRET}
            JWT_EXPIRES_IN=${JWT_EXPIRES_IN}
            OAUTH_REDIRECT_BASE=${OAUTH_REDIRECT_BASE}
            OAUTH_SUCCESS_REDIRECT=${OAUTH_SUCCESS_REDIRECT}
            OAUTH_FAILURE_REDIRECT=${OAUTH_FAILURE_REDIRECT}
            GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
            GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
            GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
            GOOGLE_CALLBACK_PATH=${GOOGLE_CALLBACK_PATH}
            NAVER_CLIENT_ID=${NAVER_CLIENT_ID}
            NAVER_CLIENT_SECRET=${NAVER_CLIENT_SECRET}
            NAVER_CALLBACK_URL=${NAVER_CALLBACK_URL}
            NAVER_CALLBACK_PATH=${NAVER_CALLBACK_PATH}
            NAVER_SERVICE_URL=${NAVER_SERVICE_URL}
            KAKAO_CLIENT_ID=${KAKAO_CLIENT_ID}
            KAKAO_CLIENT_SECRET=${KAKAO_CLIENT_SECRET}
            KAKAO_CALLBACK_URL=${KAKAO_CALLBACK_URL}
            KAKAO_CALLBACK_PATH=${KAKAO_CALLBACK_PATH}
            INITIAL_ADMIN_LOGIN_ID=${INITIAL_ADMIN_LOGIN_ID}
            INITIAL_ADMIN_PASSWORD=${INITIAL_ADMIN_PASSWORD}
            INITIAL_ADMIN_NAME=${INITIAL_ADMIN_NAME}
            INITIAL_ADMIN_EMAIL=${INITIAL_ADMIN_EMAIL}
            INITIAL_ADMIN_PHONE=${INITIAL_ADMIN_PHONE}
            AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
            AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
            AWS_REGION=${AWS_REGION}
            AWS_SES_FROM_EMAIL=${AWS_SES_FROM_EMAIL}
            AWS_SES_TO_EMAIL=${AWS_SES_TO_EMAIL}
            LOG_LEVEL=${LOG_LEVEL}
            EOL

            # pm2로 실행
            npm ci --omit=dev
            pm2 restart phoenix-backend || pm2 start dist/src/main.js --name phoenix-backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Build frontend
        run: |
          cd Frontend
          npm ci
          echo "VITE_API_BASE_URL=${{ secrets.VITE_API_BASE_URL }}" > .env.production
          echo "VITE_SCENARIO_DATA_SOURCE=${{ secrets.VITE_SCENARIO_DATA_SOURCE }}" >> .env.production
          npm run build

      - name: Copy dist to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FRONT_HOST }}
          username: ${{ secrets.FRONT_USER }}
          key: ${{ secrets.FRONT_SSH_KEY }}
          source: "Frontend/dist/*"
          target: "/home/ubuntu/apps/Phoenix/Frontend/dist"

      - name: Restart nginx
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.FRONT_HOST }}
          username: ${{ secrets.FRONT_USER }}
          key: ${{ secrets.FRONT_SSH_KEY }}
          script: |
            sudo systemctl restart nginx
